### ISSUE TITLE
Why git clone odoo?

### ISSUE THREAD

**Issue by hparfr** [sbidoul/oca-ci#3]
In this line: 
https://github.com/sbidoul/oca-ci/blob/fdbcf377efb00f94102ee5ed373ad1feab91f439/Dockerfile#L108

There is a git clone. Just wondering why not curl directly a tarball 
like https://api.github.com/repos/odoo/odoo/tarball/14.0

**Comment by sbidoul** [comment]
It might reduce the image size a bit indeed. A difficulty is to identify the root directory inside the tarball.

**Comment by sbidoul** [comment]
Done in 876f8c86b14a52eaff5eb9be0f454dc85d24b620.
